config/routes.rb
T3::Application.routes.draw do
  devise_for :users
  resources :messages, except: [:destroy, :update]
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :recipients
  belongs_to :user
  has_many :messages, through: :recipients
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :recipients
  has_many :contacts, through: :recipients
  accepts_nested_attributes_for :recipients

  def text_it
    recipients.each do |recipient|

      response = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.twilio.com/2010-04-01/Accounts/ACe14a24973eb88a9c1d231657a2550d0b/Messages.json',
        :user => 'ACe14a24973eb88a9c1d231657a2550d0b',
        :password => 'd463b5113424c2885a5803f21e1662cd',
        :payload => { :Body => body,
                      :To => Contact.find(recipient.contact_id).number,
                      :From => "3212148535"}
      ).execute

    end

    self.save
  end
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :message
  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages
  has_many :contacts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = current_user.contacts
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      current_user.contacts << @contact
      redirect_to contacts_path
    else
      render 'new'
    end
  end


private
  def contact_params
    params.require(:contact).permit(:name, :number)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    params[:message][:number].each do |key, number|
      curr_contact = Contact.find_by(number: number)

      if !curr_contact.number.empty?
        @message.recipients << Recipient.create(contact_id: curr_contact.id)
      else
        @message.recipients << Recipient.create(
                               contact_id: Contact.create(name: "unset", number: number).id)
      end
    end

    @message.text_it

    redirect_to message_path(@message)
  end

private
  def message_params
    # params.permit(:body, :number, :user_id)
    {body: params[:message][:body], user_id: params[:message][:user_id]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/contacts/index.html.erb
<h2>All Contacts for <%=current_user.email %></h2>

<ul>
<% @contacts.each do |contact| %>
  <li><ul><%= contact.name %></li>
    <li><%= contact.number %></li>
  </ul>
<% end %>
</ul>

app/views/contacts/new.html.erb
<h2>New contact</h2>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :number %>
  <%= f.text_field :number %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>T3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: "delete", class: "navbar-text pull-right" %>
        <%= link_to "Add a contact", new_contact_path, class: "navbar-text pull-right" %>
        <div class="navbar-text pull-right">
          Logged in as &nbsp; <%= link_to current_user.email, user_session_path(current_user) %>
        </div>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "navbar-text pull-right" %>
        <%= link_to "Log In", new_user_session_path, class: "navbar-text pull-right" %>
      <% end %>

    <%= yield %>


</body>
</html>

app/views/messages/index.html.erb
<h1>Text Messages</h1>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h2>New Message</h2>

<%= form_for @message do |f| %>
  <%= f.label :number %>
  <div id = "numberfield">
    <p> Contact 1 :
      <select name="message[number][1]">
        <% Contact.all.each do |contact| %>
          <option value = "<%= contact.number %>">
            <%= contact.name %> (<%= contact.number%>)
          </option>
        <% end %>
      </select>
  </div>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.submit "Send" %>
  <div class="button" id="new-number">Add another contact</div>
<% end %>

<script>
  var number_of_numbers = 1

  $(document).ready(function(){
    $('#new-number').click(function(){
      number_of_numbers += 1
      $('#numberfield').append("<p> Contact "+ number_of_numbers + " : " +
                                 "<select name='message[number][" + number_of_numbers + "]'>" +
                                   <% Contact.all.each do |contact| %>
                                     "<option value = '<%= contact.number %>'>" +
                                       "<%= contact.name %>" +
                                     "</option>" +
                                   <% end %>
                                 "</select>");
    });
  });
</script>

app/views/messages/show.html.erb
<h2>Sent Message</h2>

<%= @message.number %>
<%= @message.body %>